version: "3.8"

services:
  server:
    image: art3xa/fastapi-template:latest
    container_name: app
    build:
        context: .
        dockerfile: docker/server/Dockerfile
    ports:
        - "8000:8000"
    logging:
      driver: json-file

  tests:
    container_name: app-tests
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    restart: always
    command: "sh -c 'poetry run alembic upgrade head && poetry run uvicorn src.app.main:app --reload --workers 3 --host 0.0.0.0 --port 8000'"
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    logging:
      driver: json-file
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  autotests:
    container_name: autotests
    build:
      context: .
      dockerfile: docker/autotests/Dockerfile

  database:
    container_name: database
    image: docker.io/bitnami/postgresql:latest
    restart: always
    user: root
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    ports:
      - "5432:5432" # Remove this on production
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}

volumes:
    postgresql_data:
