name: Deploy application

on:
  workflow_run:
    workflows: [ "Static Checks" ]
    types:
      - completed
  push:
    branches:
      - '*'

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo ${{ secrets.GH_PSW }} | docker login -u ${{ secrets.GH_USR }} --password-stdin
      - name: stub env
        run: cp .env.example .env
      - name: build image
        run: |
          docker-compose build server
      - name: Push the Docker image to Docker Hub
        run: |
          docker push art3xa/fastapi-template:latest
